<?php

namespace App\Controller;

use App\Service\MarkerService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Marker rendering, so nothing has to be generated by hand and kept in a folder.
 *
 * Authenticated like the rest of /api: a marker's payload is what advances a step, so rendering
 * one is not a public capability. The admin print sheet and any MCP client both come through here,
 * which is what makes "the code on the wall" and "the string in the quest" the same thing by
 * construction.
 */
class MarkerController extends AbstractController
{
    public function __construct(
        private readonly MarkerService $markers,
    ) {
    }

    #[Route('/api/lab/markers/{value}.svg', name: 'api_lab_marker_svg', methods: ['GET'], requirements: ['value' => '.+'])]
    public function svg(string $value): Response
    {
        return new Response($this->markers->svg($value), Response::HTTP_OK, [
            'Content-Type' => 'image/svg+xml',
            // A marker is a pure function of its payload, so it caches forever; the payload
            // changing means a different URL.
            'Cache-Control' => 'private, max-age=31536000, immutable',
        ]);
    }

    #[Route('/api/lab/markers/{value}.png', name: 'api_lab_marker_png', methods: ['GET'], requirements: ['value' => '.+'])]
    public function png(string $value): Response
    {
        return new Response($this->markers->png($value), Response::HTTP_OK, [
            'Content-Type' => 'image/png',
            'Cache-Control' => 'private, max-age=31536000, immutable',
        ]);
    }
}
